# Generated by Django 3.2.6 on 2023-12-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_telegramanalysis_conclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='channel_report',
        ),
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='channel_score',
        ),
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='telegramanalysis',
            name='name',
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='alert_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telegramanalysis',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
