# Generated by Django 3.2.6 on 2023-12-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20231220_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramanalysis',
            name='measure',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
